### ISSUE TITLE
No Login

### ISSUE THREAD

**Issue by JigSawFr** [UCCNetsoc/UnFail2Ban#8]
Hey,
It could be great to allow no login with app,
As example, i've using another app for global auth and use nginx to check it before access.
Thank you !

**Comment by Strum355** [comment]
This project is currently being rewritten to not include a web UI, but instead as a central API to interact with fail2ban instances on multiple servers.

Please see [here](https://github.com/Sean-Der/fail2web) for a project that contains a web UI for interacting with fail2ban :)

**Comment by JigSawFr** [comment]
Ah great ! Thanks you for answer
Fail2web seems no longer maintained also
